name: CI/CD - Vivre aux Lilas

# Ajout des permissions
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 pytest beautifulsoup4

      - name: Create content directory
        run: |
          mkdir -p content
          echo "# Test Article" > content/2024-01-01-test.md
          echo "This is a test article" >> content/2024-01-01-test.md

      - name: Build static site
        run: |
          python script/generate.py content
          ls -la dist/

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Prepare deployment
        run: |
          mkdir -p _site
          cp -r dist/* _site/
          cp -r styles _site/
          cp -r ressource _site/
          touch _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
