name: CI/CD - Vivre aux Lilas

# Ajout des permissions
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 pytest beautifulsoup4

      - name: Create content directory
        run: |
          mkdir -p content
          echo "# Test Article" > content/2024-01-01-test.md
          echo "This is a test article" >> content/2024-01-01-test.md

      - name: Build static site
        run: |
          python script/generate.py content
          ls -la dist/  # Debug: list files in dist

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Prepare docs
        run: |
          mkdir -p docs
          cp -r dist/* docs/
          cp -r styles docs/
          cp -r ressource docs/
          touch docs/.nojekyll

      - name: List output files
        run: ls -al docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          enable_jekyll: false
