name: CI/CD Vivre aux Lilas

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2

      - name: Build static files
        run: |
          mkdir -p wwwroot
          python script/generate.py content
          cp -r dist/* wwwroot/
          cp -r styles wwwroot/
          cp -r ressource wwwroot/

      - name: List output files
        run: ls -al wwwroot

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wwwroot
          publish_branch: gh-pages
