name: CI/CD - Vivre aux Lilas

on:
  push:
    branches:
      - master # Déclenchement sur master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 pytest beautifulsoup4

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Build static site
        run: |
          python script/generate.py content
          mkdir -p docs
          cp -r dist/* docs/
          cp -r styles docs/
          cp -r ressource docs/

      - name: List output files
        run: ls -al docs

      - name: Deploy
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Deploy static site to GitHub Pages" || echo "No changes to commit"
          git push
