name: CI/CD - Vivre aux Lilas

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 pytest beautifulsoup4

      - name: Create content directory
        run: |
          mkdir -p content
          echo "# Test Article" > content/2024-01-01-test.md
          echo "This is a test article." >> content/2024-01-01-test.md

      - name: Build static site
        run: |
          python script/generate.py content
          ls -la dist/  # Affiche le contenu de dist pour debug

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Prepare docs
        run: |
          mkdir -p docs
          cp -r dist/* docs/       
          cp -r styles docs/       
          cp -r ressource docs/    
          touch docs/.nojekyll     
          ls -al docs

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Deploy static site to docs folder" || echo "No changes to commit"
          git push origin master
